function [paramsInitialization,paramsContinuous] = loadMalagaParams()
%LOADKITTIPARAMS Summary of this function goes here
%   Detailed explanation goes here

% initialization parameters MALAGA
paramsInitialization = struct (...
...% Harris detection parameters
'MinQuality', 20e-5, ...               
'FilterSize', 15, ...
... % Ransac fundamental matrix parameters
'NumTrials', 3000, ...              
'DistanceThreshold', 0.2, ...
... % KLT tracking parameters
'BlockSizeKLT',[15 15], ...            
'MaxIterations',30, ...         
'NumPyramidLevels',3, ...
'MaxBidirectionalError',1 ...  
);

% processFrame parameters MALAGA
paramsContinuous = struct (...
... % KLT parameters
'BlockSize',[21 21], ...            
'MaxIterations',15, ...         
'NumPyramidLevels',3, ...
'MaxBidirectionalError',1,... %%% REMOVES POINTS WHEN NOT TRACKED ANYMORE (vision.PointTracker)   
... % P3P parameters 
'MaxNumTrialsPnP',1000, ...            
'ConfidencePnP',90,...
'MaxReprojectionErrorPnP', 2, ...
... % Triangulation parameters
'AlphaThreshold', 6 *pi/180, ...   %Min baseline angle [rad] for new landmark (alpha(c) in pdf)
... % Harris paramters for canditate keypoint exraction
'MinQuality', 20e-5, ... % higher => less keypoints
'FilterSize', 21, ...
... % Matching parameters for duplicate keypoint removal
'BlockSizeHarris', 15, ... % feature extraction parameters
'MaxRatio', 1.00,... % higehr => more matches
'MatchThreshold', 100.0,...  % higher  => more matches  
'Unique', false, ...
... % Minimum pixel distance between new candidates and existing keypoints
'MinDistance', 11 ...
);
end